test(halo): rename storyshots file for ts
error TS2345: Argument of type '{ createNodeMock: () => HTMLDivElement; }' is not assignable to parameter of type 'Function | { renderer?: any; serializer?: any; }'.
  Object literal may only specify known properties, and 'createNodeMock' does not exist in type 'Function | { renderer?: any; serializer?: any; }'.

14   test: snapshotWithOptions({ createNodeMock })